# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-20 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
