# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-20 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
